# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-US'
early_access: false
reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: false
  estimate_code_review_effort: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    github-checks:
      enabled: true
      timeout_ms: 300000
chat:
  auto_reply: true
