default_platform(:android)

platform :android do
  ##############################################
  ####              Utilities                ###
  ##############################################

  desc "Verify that the current build has new user facing features"
  private_lane :verify do
    analyze_commits(
      match: "*"
    )
  end

  ##############################################
  ####             Build steps               ###
  ##############################################

  desc "Util to build the app for all flavors"
  private_lane :build do |options|
    if options[:task]
      android_set_version_code(
        version_code: Time.now.utc.strftime("%Y%m%d.%H%M.%S"),
      )
      gradle(
        tasks: ["clean", options[:task]],
      )
    else
      UI.error "`task` option is required"
    end
  end

  ##############################################
  ####               CI steps                ###
  ##############################################

  desc "Create and upload a Staging build"
  lane :release_staging do
    if verify
      build(
        task: "assembleStagingRelease",
      )
      appcenter_upload(
        api_token: ENV["APPCENTER_API_TOKEN"],
        owner_type: ENV["APPCENTER_OWNER_TYPE"],
        owner_name: ENV["APPCENTER_OWNER_NAME"],
        app_name: ENV["APPCENTER_APP_NAME"],
        notify_testers: false,
        release_notes: sh(
          log: false,
          command: "yarn version:changelog",
        ),
      )
    else
      UI.error "No user facing changes since the last release!"
    end
  end

  desc "Create and upload a Production build"
  lane :release_production do
    if verify
      build(
        task: "bundleProductionRelease",
      )
      upload_to_play_store(
        track: "alpha",
        release_status: "draft",
        skip_upload_apk: true,
        validate_only: false,
        json_key_data: ENV["ANDROID_JSON_KEY"],
      )
    else
      UI.error "No user facing changes since the last release!"
    end
  end
end