name: Build the app for development

on: workflow_dispatch

jobs:
  build_dev_app:
    name: Build the app for development
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check for EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: 23.0.0
          token: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Build
        run: eas build --platform all --non-interactive --profile development --no-wait
