name: Quality

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'

      - name: Check node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install JS dependencies if not cached
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run quality checks
        run: |
          yarn test
          yarn tsc
          yarn lint

      - name: Run DangerJS
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: yarn danger ci
