name: Tag

on:
  pull_request:
    types:
      - labeled

jobs:
  tag:
    if: ${{ github.event.label.name == 'deployed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Git credentials
        run: |
          git config user.email "$(git log --format='%ae' HEAD^!)"
          git config user.name "$(git log --format='%an' HEAD^!)"

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'

      - name: Update the app version and tag it
        run: npx standard-version

      - name: Commit the changes
        run: git push --follow-tags
