name: Add testers

on:
  pull_request:
    types:
      - labeled

jobs:
  tag:
    if: ${{ github.event.label.name == 'add testers' }}
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add a Deploy Key to access the Match repo
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check Bundler cache
        uses: actions/cache@v2
        with:
          path: ios/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gem dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: ios

      - name: Populate the Fastlane env file
        run: |
          echo "${{secrets.FASTLANE_ENV_IOS}}" > .env.fastlane.ios.asc
          gpg -d --passphrase "${{secrets.FASTLANE_ENV_IOS_PASSPHRASE}}" --batch .env.fastlane.ios.asc > fastlane/.env
        working-directory: ios

      - name: Create a temporary Keychain
        run: bundle exec fastlane keychain_setup
        working-directory: ios

      - name: Check for new devices and regenerate certificates
        run: bundle exec fastlane add_testers is_ci:true
        working-directory: ios
